source 'https://rubygems.org'

gem 'jekyll', '~> 3.8'

gem 'jekyll-theme-fuji', git: 'https://github.com/fuji-nakahara/jekyll-theme-fuji.git'

group :jekyll_plugins do
  gem 'jekyll-build-ebook', '~> 0.3'
  gem 'jekyll-fuji_markdown'
end

group :test do
  gem 'html-proofer'
end
