# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
author: フジ・ナカハラ
description: >- # this means to ignore newlines until "url:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /jekyll-theme-fuji # the subpath of your site, e.g. /blog
url: https://fuji-nakahara.github.io # the base hostname & protocol for your site, e.g. http://example.com
version: 0.1.0
timezone: Asia/Tokyo
lang: ja_JP

# Build settings
markdown: kramdown
theme: jekyll-theme-fuji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Theme settings
homepage: https://fuji-nakahara.github.io/
repository: fuji-nakahara/jekyll-theme-fuji
google_analytics: UA-118273401-1
show_ebooks_from_github_releases: false
reverse_posts_order: false
show_excerpts: true
show_date: true
date_format: "%Y年%m月%d日"
header_pages:
  - about.md
